import type { CvData, CvStyle, CvTemplate, Language } from "@nomcci/cvmaker-domain";

const LABELS = {
  es: { profile: "Perfil", experience: "Experiencia", professionalExperience: "Experiencia Profesional", education: "Educacion", skills: "Habilidades", languages: "Idiomas", contact: "Contacto" },
  en: { profile: "Profile", experience: "Experience", professionalExperience: "Professional Experience", education: "Education", skills: "Skills", languages: "Languages", contact: "Contact" },
};

export function renderCvHtml(cv: CvData, input: { style: CvStyle; template: CvTemplate; language: Language }): string {
  const css = styles[input.style];
  return input.template === "cv_sidebar" ? sidebarTemplate(cv, css, input.language) : baseTemplate(cv, css, input.language);
}

const A4_LAYOUT = `@page { size: A4; margin: 0; } html, body { width: 210mm; min-height: 297mm; } .cv-page { width: 210mm !important; max-width: none !important; min-height: 297mm; margin: 0 !important; } .sidebar-page { display: flex; flex-direction: column; } .sidebar-page .content-grid { flex: 1 0 auto; grid-template-columns: 30% 1fr !important; align-items: stretch; } @media print { html, body, .cv-page { width: 210mm !important; min-height: 297mm; } }`;

function baseTemplate(cv: CvData, css: string, language: Language): string {
  const t = LABELS[language];
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(cv.personal_info.full_name)} - CV</title><style>${css}${A4_LAYOUT}</style></head><body><main class="cv-page"><header class="hero"><div><h1>${e(cv.personal_info.full_name)}</h1>${cv.personal_info.title ? `<p class="title">${e(cv.personal_info.title)}</p>` : ""}</div><ul class="contact">${contact(cv)}</ul></header>${cv.summary ? `<section><h2>${t.profile}</h2><p>${e(cv.summary)}</p></section>` : ""}${experience(cv, t.experience)}${education(cv, t.education)}<section class="columns">${skills(cv, t.skills)}${languages(cv, t.languages, "compact-list")}</section></main></body></html>`;
}

function sidebarTemplate(cv: CvData, css: string, language: Language): string {
  const t = LABELS[language];
  return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(cv.personal_info.full_name)} - CV</title><style>${css}${A4_LAYOUT}</style></head><body><main class="cv-page sidebar-page"><header class="hero">${photo(cv)}<div><h1>${e(cv.personal_info.full_name)}</h1>${cv.personal_info.title ? `<p class="title">${e(cv.personal_info.title)}</p>` : ""}</div></header><div class="content-grid"><aside class="sidebar"><section><h2>${t.contact}</h2><ul class="plain-list">${contact(cv)}</ul></section>${skills(cv, t.skills)}${languages(cv, t.languages, "plain-list")}</aside><section class="main-column">${cv.summary ? `<section><h2>${t.profile}</h2><p>${e(cv.summary)}</p></section>` : ""}${education(cv, t.education)}${experience(cv, t.professionalExperience, "spaced-bullets")}</section></div></main></body></html>`;
}

function photo(cv: CvData): string {
  const url = cv.personal_info.photo_url;
  return url ? `<img class="profile-photo" src="${e(url)}" alt="">` : "";
}

function contact(cv: CvData): string {
  const p = cv.personal_info;
  return [p.email, p.phone, p.location].filter(Boolean).map((v) => `<li>${e(v)}</li>`).join("") + (p.links || []).map((link) => `<li><a href="${e(link.url)}">${e(link.label)}</a></li>`).join("");
}

function experience(cv: CvData, title: string, listClass = ""): string {
  if (!cv.experience?.length) return "";
  return `<section><h2>${title}</h2>${cv.experience.map((item) => `<article class="entry"><div class="entry-heading"><div><h3>${e(item.role)}</h3><p class="meta">${e(item.company)}${item.location ? ` · ${e(item.location)}` : ""}</p></div><p class="date">${e(item.start_date)}${item.end_date ? ` - ${e(item.end_date)}` : ""}</p></div>${item.description?.length ? `<ul${listClass ? ` class="${listClass}"` : ""}>${item.description.map((point) => `<li>${e(point)}</li>`).join("")}</ul>` : ""}</article>`).join("")}</section>`;
}

function education(cv: CvData, title: string): string {
  if (!cv.education?.length) return "";
  return `<section><h2>${title}</h2>${cv.education.map((item) => `<article class="entry"><div class="entry-heading"><div><h3>${e(item.degree)}</h3><p class="meta">${e(item.institution)}${item.location ? ` · ${e(item.location)}` : ""}</p></div><p class="date">${e(item.start_date)}${item.end_date ? ` - ${e(item.end_date)}` : ""}</p></div>${item.details?.length ? `<ul>${item.details.map((detail) => `<li>${e(detail)}</li>`).join("")}</ul>` : ""}</article>`).join("")}</section>`;
}

function skills(cv: CvData, title: string): string {
  if (!cv.skills?.length) return "";
  return `<div><h2>${title}</h2>${cv.skills.map((group) => `<div class="skill-group"><h3>${e(group.name)}</h3><p>${(group.items || []).map(e).join(", ")}</p></div>`).join("")}</div>`;
}

function languages(cv: CvData, title: string, className: string): string {
  if (!cv.languages?.length) return "";
  return `<div><h2>${title}</h2><ul class="${className}">${cv.languages.map((language) => `<li>${e(language.name)}${language.level ? ` · ${e(language.level)}` : ""}</li>`).join("")}</ul></div>`;
}

function e(value: unknown): string {
  return String(value || "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}

const styles: Record<CvStyle, string> = {
  modern: `@page { size: A4; margin: 18mm; } * { box-sizing: border-box; } body { margin: 0; background: #eef2f7; color: #182033; font-family: Arial, Helvetica, sans-serif; line-height: 1.45; } a { color: #2563eb; text-decoration: none; } .cv-page { max-width: 900px; margin: 0 auto; background: #ffffff; padding: 36px; } .hero { display: flex; justify-content: space-between; gap: 32px; border-bottom: 4px solid #2563eb; padding-bottom: 20px; } h1 { margin: 0; font-size: 38px; letter-spacing: -1px; } .title { margin: 8px 0 0; color: #2563eb; font-size: 18px; font-weight: 700; } .contact { margin: 0; padding: 0; list-style: none; color: #475569; text-align: right; font-size: 13px; } section { margin-top: 26px; } h2 { margin: 0 0 12px; color: #111827; font-size: 14px; letter-spacing: 1.8px; text-transform: uppercase; } h3 { margin: 0; font-size: 17px; } .meta, .date { margin: 4px 0 0; color: #64748b; font-size: 13px; } .entry { margin-bottom: 18px; } .entry-heading { display: flex; justify-content: space-between; gap: 18px; } ul { margin: 8px 0 0; padding-left: 20px; } li { margin-bottom: 5px; } .columns { display: grid; grid-template-columns: 2fr 1fr; gap: 34px; } .skill-group { margin-bottom: 12px; } .skill-group p { margin: 4px 0 0; } .compact-list { padding-left: 18px; } @media print { body { background: #fff; } .cv-page { max-width: none; padding: 0; } } @media (max-width: 700px) { .cv-page { padding: 24px; } .hero, .entry-heading { display: block; } .contact { margin-top: 16px; text-align: left; } .columns { grid-template-columns: 1fr; } }`,
  minimal: `@page { size: A4; margin: 18mm; } * { box-sizing: border-box; } body { margin: 0; color: #111; font-family: Georgia, serif; line-height: 1.4; } a { color: #111; } .cv-page { max-width: 850px; margin: 0 auto; padding: 34px; } .hero { border-bottom: 1px solid #111; padding-bottom: 14px; } h1 { margin: 0; font-size: 34px; } .title, .meta, .date { color: #555; } .contact { list-style: none; padding: 0; font-size: 13px; } section { margin-top: 22px; } h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 1.4px; } h3 { margin: 0; } .entry-heading { display: flex; justify-content: space-between; gap: 18px; } .columns { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; } @media print { .cv-page { padding: 0; } } @media (max-width: 700px) { .entry-heading, .columns { display: block; } }`,
  classic: `@page { size: A4; margin: 18mm; } * { box-sizing: border-box; } body { margin: 0; background: #f7f3ea; color: #211a14; font-family: 'Times New Roman', Times, serif; line-height: 1.42; } a { color: #7c2d12; } .cv-page { max-width: 860px; margin: 0 auto; background: #fffaf0; padding: 36px; border: 1px solid #d6c3a5; } .hero { text-align: center; border-bottom: 2px solid #7c2d12; padding-bottom: 18px; } h1 { margin: 0; font-size: 36px; } .title { font-style: italic; } .contact { list-style: none; padding: 0; font-size: 13px; } section { margin-top: 24px; } h2 { color: #7c2d12; font-size: 15px; text-transform: uppercase; } h3 { margin: 0; } .entry-heading { display: flex; justify-content: space-between; gap: 18px; } .meta, .date { color: #6b5b4b; } .columns { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; } @media print { body { background: #fff; } .cv-page { border: 0; padding: 0; } } @media (max-width: 700px) { .entry-heading, .columns { display: block; } }`,
  sidebar_compact: `@page { size: A4; margin: 9mm; } * { box-sizing: border-box; } body { margin: 0; color: #172033; background: #ffffff; font-family: Arial, Helvetica, sans-serif; font-size: 9.2px; line-height: 1.28; } a { color: #1d4ed8; text-decoration: none; } .cv-page { width: 100%; max-width: 780px; margin: 0 auto; } .hero { display: flex; align-items: center; gap: 12px; padding: 0 0 8px; margin-bottom: 10px; border-bottom: 2px solid #1d4ed8; } .profile-photo { width: 58px; height: 58px; border-radius: 18px; object-fit: cover; border: 1px solid #cbd5e1; } h1 { margin: 0; font-size: 23px; line-height: 1; letter-spacing: .3px; } .title { margin: 3px 0 0; color: #1d4ed8; font-size: 11px; font-weight: 700; text-transform: uppercase; } .content-grid { display: grid; grid-template-columns: 30% 1fr; gap: 14px; align-items: start; } .sidebar { padding-right: 12px; border-right: 1px solid #cbd5e1; color: #334155; } section { margin: 0 0 10px; } h2 { margin: 0 0 5px; color: #0f172a; font-size: 9.5px; letter-spacing: 1.2px; text-transform: uppercase; } h3 { margin: 0; color: #111827; font-size: 10px; line-height: 1.2; } p { margin: 0; } .plain-list { margin: 0; padding: 0; list-style: none; overflow-wrap: anywhere; } .plain-list li { margin-bottom: 3px; } .skill-group { margin-bottom: 6px; } .skill-group p { margin-top: 2px; } .main-column section { margin-bottom: 9px; } .entry { margin-bottom: 8px; break-inside: avoid; } .entry-heading { display: grid; grid-template-columns: 1fr auto; gap: 10px; align-items: start; } .meta { margin-top: 2px; color: #475569; font-size: 9.2px; font-weight: 700; } .date { color: #64748b; font-size: 8.8px; white-space: nowrap; text-align: right; } .spaced-bullets { margin: 4px 0 0; padding-left: 0; list-style: none; } .spaced-bullets li { position: relative; margin-bottom: 2.5px; padding-left: 13px; } .spaced-bullets li::before { content: "-"; position: absolute; left: 0; color: #64748b; } @media screen and (max-width: 700px) { body { font-size: 12px; } .content-grid { grid-template-columns: 1fr; } .sidebar { padding-right: 0; border-right: 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 10px; } .entry-heading { grid-template-columns: 1fr; } .date { text-align: left; } }`,
  executive: `@page { size: A4; margin: 16mm; } * { box-sizing: border-box; } body { margin: 0; color: #17201a; background: #edf2ed; font-family: Arial, Helvetica, sans-serif; line-height: 1.42; } a { color: #0d5f46; text-decoration: none; } .cv-page { max-width: 900px; margin: 0 auto; background: #fffdf8; padding: 0 36px 36px; } .hero { margin: 0 -36px; padding: 34px 36px 28px; background: #17201a; color: #fffaf1; } h1 { margin: 0; font-size: 39px; letter-spacing: -.8px; } .title { margin: 8px 0 0; color: #9ae6c4; font-size: 17px; font-weight: 700; } .contact { display: flex; flex-wrap: wrap; gap: 10px 18px; margin: 18px 0 0; padding: 0; list-style: none; color: #d9e4d9; font-size: 12px; } section { margin-top: 24px; } h2 { margin: 0 0 10px; color: #0d5f46; font-size: 13px; letter-spacing: 1.6px; text-transform: uppercase; } h3 { margin: 0; font-size: 16px; } .meta, .date { margin: 4px 0 0; color: #69746d; font-size: 13px; } .entry { margin-bottom: 16px; border-left: 3px solid #8ee0bc; padding-left: 12px; } .entry-heading { display: flex; justify-content: space-between; gap: 18px; } ul { margin: 8px 0 0; padding-left: 20px; } li { margin-bottom: 4px; } .columns { display: grid; grid-template-columns: 1.45fr 1fr; gap: 30px; border-top: 1px solid #d8e2d9; padding-top: 4px; } .skill-group { margin-bottom: 10px; } .skill-group p { margin: 4px 0 0; } @media print { body { background: #fff; } .cv-page { max-width: none; } } @media (max-width: 700px) { .cv-page { padding: 0 24px 24px; } .hero { margin: 0 -24px; padding: 28px 24px; } .entry-heading, .columns { display: block; } }`,
  sidebar_green: `@page { size: A4; margin: 9mm; } * { box-sizing: border-box; } body { margin: 0; color: #173028; background: #ffffff; font-family: Arial, Helvetica, sans-serif; font-size: 9.2px; line-height: 1.3; } a { color: #d7f7e6; text-decoration: none; } .cv-page { width: 100%; max-width: 780px; margin: 0 auto; } .hero { display: flex; align-items: center; gap: 12px; padding: 0 0 10px; margin-bottom: 10px; border-bottom: 3px solid #0d5f46; } .profile-photo { width: 58px; height: 58px; border-radius: 18px; object-fit: cover; border: 2px solid #8ee0bc; } h1 { margin: 0; font-size: 23px; line-height: 1; letter-spacing: .3px; } .title { margin: 3px 0 0; color: #0d5f46; font-size: 11px; font-weight: 700; text-transform: uppercase; } .content-grid { display: grid; grid-template-columns: 30% 1fr; gap: 14px; align-items: stretch; } .sidebar { min-height: 100%; margin-left: -2px; padding: 12px; background: #0d5f46; color: #e8fff1; } .sidebar h2, .sidebar h3 { color: #ffffff; } .sidebar .skill-group p { color: #c9f2d9; } section { margin: 0 0 10px; } h2 { margin: 0 0 5px; color: #0d5f46; font-size: 9.5px; letter-spacing: 1.2px; text-transform: uppercase; } h3 { margin: 0; color: #173028; font-size: 10px; line-height: 1.2; } p { margin: 0; } .plain-list { margin: 0; padding: 0; list-style: none; overflow-wrap: anywhere; } .plain-list li { margin-bottom: 3px; } .skill-group { margin-bottom: 6px; } .skill-group p { margin-top: 2px; } .main-column section { margin-bottom: 9px; } .entry { margin-bottom: 8px; break-inside: avoid; } .entry-heading { display: grid; grid-template-columns: 1fr auto; gap: 10px; align-items: start; } .meta { margin-top: 2px; color: #3b5a4e; font-size: 9.2px; font-weight: 700; } .date { color: #61796d; font-size: 8.8px; white-space: nowrap; text-align: right; } .spaced-bullets { margin: 4px 0 0; padding-left: 0; list-style: none; } .spaced-bullets li { position: relative; margin-bottom: 2.5px; padding-left: 13px; } .spaced-bullets li::before { content: "-"; position: absolute; left: 0; color: #0d5f46; } @media screen and (max-width: 700px) { body { font-size: 12px; } .content-grid { grid-template-columns: 1fr; } .sidebar { margin: 0; } }`,
};
